map_tools:
  ros__parameters:
    map_yaml: /home/gosunwoo/fire_robot_rpi/maps/inno_map_raw.yaml
    zones_yaml: /home/gosunwoo/fire_robot_rpi/maps/no_go_zones.yaml
    out_dir: /home/gosunwoo/fire_robot_rpi/maps
    output_file: /home/gosunwoo/fire_robot_rpi/maps/clicked_points_debug.yaml
    topic: /clicked_point
    expected_frame: map
